


name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main


     # ✅ Check if WASM file exists and decompress it
      - name: Decompress .wasm file
        run: |
          curl -L https://raw.githubusercontent.com/minec-c/satnotcanvasxz/main/wasm1/exportgodotlab.wasm.gz -o exportgodotlab.wasm.gz
          
          if [ -f exportgodotlab.wasm.gz ]; then
            echo "WASM file found ✅"
            
          else
            echo "WASM file NOT found ❌"
            exit 1
          fi
          
          gzip -d exportgodotlab.wasm.gz || { echo "Decompression failed ❌"; exit 1; }
          if [ -f exportgodotlab.wasm ]; then
            echo "WASM file decompressed ✅"
          else
            echo "WASM file NOT decompressed ❌"
            exit 1
          fi

          mkdir -p wasm1
          mv exportgodotlab.wasm wasm1/exportgodotlab.wasm
          
      - name: Download and decompress .pck file directly
        run: |
          curl -L https://raw.githubusercontent.com/minec-c/trinityrepo/main/godotapk/exportgodotlab.pck.gz -o exportgodotlab.pck.gz

          if [ -f exportgodotlab.pck.gz ]; then
            echo "PCK file downloaded ✅"
          else
            echo "PCK file NOT downloaded ❌"
            exit 1
          fi


          gzip -d exportgodotlab.pck.gz || { echo "Decompression failed ❌"; exit 1; }
          if [ -f exportgodotlab.pck ]; then
            echo "PCK file decompressed ✅"
          else
            echo "PCK file NOT decompressed ❌"
            exit 1
          fi

          mkdir -p godotapk
          mv exportgodotlab.pck godotapk/exportgodotlab.pck

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # Upload everything from the main working directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
